@extends('layouts.app')

@section('content')
    @include('components.landing.hero-section')
    @include('components.landing.partner-section')
    @include('components.landing.aboutus-section')
    @include('components.landing.feature-section')
    @include('components.landing.whatget-section')
    @include('components.landing.integrate-section')
    @include('components.landing.plan-section')
    @include('components.landing.testimonial-section')
    @include('components.landing.cta-section')
    @include('components.landing.faq-section')
    @include('components.landing.main-cta')
@endsection
